### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by maryush** [adamjgrant/kickstart#106]
Hi, I'm use Win 8.1, and after type kickstrap new . I have error:

Copying in Kickstrap files...
Compiling via Roots and launching server...
compiling... mshell.js: internal error
Error: ENOENT, no such file or directory 'C:\xampp\htdocs\ks01\public:'
    at Object.fs.mkdirSync (fs.js:642:18)
    at mkdirSyncRecursive (C:\Users\Mariusz\AppData\Roaming\npm\node_modules\roots\node_modules\shelljs\src\mkdir.js:11:8)
    at mkdirSyncRecursive (C:\Users\Mariusz\AppData\Roaming\npm\node_modules\roots\node_modules\shelljs\src\mkdir.js:16:3)
    at mkdirSyncRecursive (C:\Users\Mariusz\AppData\Roaming\npm\node_modules\roots\node_modules\shelljs\src\mkdir.js:16:3)
    at mkdirSyncRecursive (C:\Users\Mariusz\AppData\Roaming\npm\node_modules\roots\node_modules\shelljs\src\mkdir.js:16:3)
    at mkdirSyncRecursive (C:\Users\Mariusz\AppData\Roaming\npm\node_modules\roots\node_modules\shelljs\src\mkdir.js:16:3)
    at mkdirSyncRecursive (C:\Users\Mariusz\AppData\Roaming\npm\node_modules\roots\node_modules\shelljs\src\mkdir.js:16:3)
    at C:\Users\Mariusz\AppData\Roaming\npm\node_modules\roots\node_modules\shelljs\src\mkdir.js:63:7
    at Array.forEach (native)
    at Object._mkdir (C:\Users\Mariusz\AppData\Roaming\npm\node_modules\roots\node_modules\shelljs\src\mkdir.js:48:8)
    at Object.mkdir (C:\Users\Mariusz\AppData\Roaming\npm\node_modules\roots\node_modules\shelljs\src\common.js:172:23)
    at create_folders (C:\Users\Mariusz\AppData\Roaming\npm\node_modules\roots\lib\index.js:115:13)
    at C:\Users\Mariusz\AppData\Roaming\npm\node_modules\roots\node_modules\when\function.js:63:16
    at Promise.FulfilledPromise._when (C:\Users\Mariusz\AppData\Roaming\npm\node_modules\roots\node_modules\when\when.js:447:48)
    at Array.deliver [as 0](C:UsersMariuszAppDataRoamingnpmnode_modulesrootsnode_moduleswhenwhen.js:108:7)
    at runHandlers (C:\Users\Mariusz\AppData\Roaming\npm\node_modules\roots\node_modules\when\when.js:370:12)
    at Array.8 (C:\Users\Mariusz\AppData\Roaming\npm\node_modules\roots\node_modules\when\when.js:130:5)
    at runHandlers (C:\Users\Mariusz\AppData\Roaming\npm\node_modules\roots\node_modules\when\when.js:370:12)
    at drainQueue (C:\Users\Mariusz\AppData\Roaming\npm\node_modules\roots\node_modules\when\when.js:819:3)
    at process._tickCallback (node.js:419:13)
"ctrl + c" to quit watching
"roots watch" to watch project again.

Probably error it's from ':' char in path...
roots in version 2.1.3

**Comment by bretonio** [comment]
My case is nearly exactly parallel except that I am on Debian Linux. 

```
kickstart compile
kickstart watch
Cannot get /
```
and

```
roots compile
roots watch
Cannot get /
```
My other Roots projects are compiling and serving fine. The file structure created by `kickstrap new my-kickstrap` looks correct.

```bash
├── app.coffee
├── assets
│   ├── apps
│   │   ├── advertisements
│   │   │   ├── main.coffee
│   │   │   ├── markup.txt
│   │   │   └── responsive.css
│   │   ├── ang-app
│   │   │   ├── controllers
│   │   │   │   ├── docs.coffee
│   │   │   │   ├── home.coffee
│   │   │   │   ├── login.coffee
│   │   │   │   ├── messages.coffee
│   │   │   │   ├── module.coffee
│   │   │   │   └── products.coffee
│   │   │   ├── directives
│   │   │   │   ├── enter.coffee
│   │   │   │   ├── module.coffee
│   │   │   │   ├── repeat.coffee
│   │   │   │   └── visible.coffee
│   │   │   ├── filters
│   │   │   │   ├── module.coffee
│   │   │   │   └── startFrom.coffee
│   │   │   ├── main.coffee
│   │   │   └── resources
│   │   │       ├── angular-route.js
│   │   │       ├── firebaseSimpleLogin.js
│   │   │       ├── gatedScope.js
│   │   │       └── ngprogress.js
│   │   ├── disqus
│   │   │   ├── main.coffee
│   │   │   └── markup.txt
│   │   ├── kickstrap-logo
│   │   │   ├── kickstraplogo-regular-webfont.eot
│   │   │   ├── kickstraplogo-regular-webfont.svg
│   │   │   ├── kickstraplogo-regular-webfont.ttf
│   │   │   ├── kickstraplogo-regular-webfont.woff
│   │   │   ├── main.coffee
│   │   │   ├── specimen_files
│   │   │   │   ├── easytabs.js
│   │   │   │   ├── grid_12-825-55-15.css
│   │   │   │   └── specimen_stylesheet.css
│   │   │   └── stylesheet.css
│   │   ├── pong
│   │   │   ├── description.txt
│   │   │   ├── game.txt
│   │   │   ├── main.js
│   │   │   └── style.css
│   │   ├── sample-app
│   │   │   ├── main.coffee
│   │   │   └── sample-app.css
│   │   └── tinygrowl
│   │       └── main.coffee
│   ├── css
│   │   ├── _auth-buttons.styl
│   │   └── main.styl
│   ├── fonts
│   │   ├── glyphicons-halflings-regular.eot
│   │   ├── glyphicons-halflings-regular.svg
│   │   ├── glyphicons-halflings-regular.ttf
│   │   └── glyphicons-halflings-regular.woff
│   ├── img
│   │   ├── abergs.png
│   │   ├── angular.png
│   │   ├── auth-icons.png
│   │   ├── creditcards.gif
│   │   ├── dzone.png
│   │   ├── firebase.png
│   │   ├── fwdslash.png
│   │   ├── hn.png
│   │   ├── ipreo.png
│   │   ├── jspm.png
│   │   ├── kickstrap-logo.png
│   │   ├── kickstrap-logo_small_brown.png
│   │   ├── loading.png
│   │   ├── mashable.png
│   │   ├── peugeot.png
│   │   ├── poster.png
│   │   ├── skuvault.png
│   │   ├── t3n.png
│   │   └── vegankit.png
│   ├── js
│   │   ├── _badge.coffee
│   │   ├── _extend.coffee
│   │   ├── kickstrap.coffee
│   │   └── _settings.coffee
│   └── themes
│       ├── amelia.css
│       ├── amelia.png
│       ├── bootstrap.css
│       ├── bootstrap.png
│       ├── cerulean.css
│       ├── cerulean.png
│       ├── cosmo.css
│       ├── cosmo.png
│       ├── cyborg.css
│       ├── cyborg.png
│       ├── flatly.css
│       ├── flatly.png
│       ├── journal.css
│       ├── journal.png
│       ├── kickstrap.css
│       ├── kickstrap.png
│       ├── readable.css
│       ├── readable.png
│       ├── simplex.css
│       ├── simplex.png
│       ├── slate.css
│       ├── slate.png
│       ├── spacelab.css
│       ├── spacelab.png
│       ├── united.css
│       ├── united.png
│       ├── yeti.css
│       └── yeti.png
├── kickstrap-demo-data.json
├── public
│   ├── apps
│   │   ├── advertisements
│   │   │   ├── main.coffee
│   │   │   ├── markup.txt
│   │   │   └── responsive.css
│   │   ├── ang-app
│   │   │   ├── controllers
│   │   │   │   ├── docs.coffee
│   │   │   │   ├── home.coffee
│   │   │   │   ├── login.coffee
│   │   │   │   ├── messages.coffee
│   │   │   │   ├── module.coffee
│   │   │   │   └── products.coffee
│   │   │   ├── directives
│   │   │   │   ├── enter.coffee
│   │   │   │   ├── module.coffee
│   │   │   │   ├── repeat.coffee
│   │   │   │   └── visible.coffee
│   │   │   ├── filters
│   │   │   │   ├── module.coffee
│   │   │   │   └── startFrom.coffee
│   │   │   ├── main.coffee
│   │   │   └── resources
│   │   │       ├── angular-route.js
│   │   │       ├── firebaseSimpleLogin.js
│   │   │       ├── gatedScope.js
│   │   │       └── ngprogress.js
│   │   ├── disqus
│   │   │   ├── main.coffee
│   │   │   └── markup.txt
│   │   ├── kickstrap-logo
│   │   │   ├── kickstraplogo-regular-webfont.eot
│   │   │   ├── kickstraplogo-regular-webfont.svg
│   │   │   ├── kickstraplogo-regular-webfont.ttf
│   │   │   ├── kickstraplogo-regular-webfont.woff
│   │   │   ├── main.coffee
│   │   │   ├── specimen_files
│   │   │   │   ├── easytabs.js
│   │   │   │   ├── grid_12-825-55-15.css
│   │   │   │   └── specimen_stylesheet.css
│   │   │   └── stylesheet.css
│   │   ├── pong
│   │   │   ├── description.txt
│   │   │   ├── game.txt
│   │   │   ├── main.js
│   │   │   └── style.css
│   │   ├── sample-app
│   │   │   ├── main.coffee
│   │   │   └── sample-app.css
│   │   └── tinygrowl
│   │       └── main.coffee
│   ├── blank.jade
│   ├── cart.jade
│   ├── css
│   │   ├── _auth-buttons.styl
│   │   └── main.styl
│   ├── docs.jade
│   ├── _example-growl.jade
│   ├── fonts
│   │   ├── glyphicons-halflings-regular.eot
│   │   ├── glyphicons-halflings-regular.svg
│   │   ├── glyphicons-halflings-regular.ttf
│   │   └── glyphicons-halflings-regular.woff
│   ├── _header.jade
│   ├── img
│   │   ├── abergs.png
│   │   ├── angular.png
│   │   ├── auth-icons.png
│   │   ├── creditcards.gif
│   │   ├── dzone.png
│   │   ├── firebase.png
│   │   ├── fwdslash.png
│   │   ├── hn.png
│   │   ├── ipreo.png
│   │   ├── jspm.png
│   │   ├── kickstrap-logo.png
│   │   ├── kickstrap-logo_small_brown.png
│   │   ├── loading.png
│   │   ├── mashable.png
│   │   ├── peugeot.png
│   │   ├── poster.png
│   │   ├── skuvault.png
│   │   ├── t3n.png
│   │   └── vegankit.png
│   ├── index.jade
│   ├── js
│   │   ├── _badge.coffee
│   │   ├── _extend.coffee
│   │   ├── kickstrap.coffee
│   │   └── _settings.coffee
│   ├── kickstrap-demo-data.json
│   ├── layout.jade
│   ├── messages.jade
│   ├── newpage.jade
│   ├── _pagination.jade
│   ├── partials
│   │   ├── acknowledgments.jade
│   │   ├── api.jade
│   │   ├── apps.jade
│   │   ├── coffeescript.jade
│   │   ├── first-steps.jade
│   │   ├── growls.jade
│   │   ├── jade.jade
│   │   ├── optimizations.jade
│   │   ├── pages.jade
│   │   ├── partials.jade
│   │   ├── roots.jade
│   │   ├── social-login.jade
│   │   ├── stylus.jade
│   │   └── templates.jade
│   ├── products.jade
│   ├── readme.md
│   └── themes
│       ├── amelia.css
│       ├── amelia.png
│       ├── bootstrap.css
│       ├── bootstrap.png
│       ├── cerulean.css
│       ├── cerulean.png
│       ├── cosmo.css
│       ├── cosmo.png
│       ├── cyborg.css
│       ├── cyborg.png
│       ├── flatly.css
│       ├── flatly.png
│       ├── journal.css
│       ├── journal.png
│       ├── kickstrap.css
│       ├── kickstrap.png
│       ├── readable.css
│       ├── readable.png
│       ├── simplex.css
│       ├── simplex.png
│       ├── slate.css
│       ├── slate.png
│       ├── spacelab.css
│       ├── spacelab.png
│       ├── united.css
│       ├── united.png
│       ├── yeti.css
│       └── yeti.png
├── readme.md
├── tree.txt
└── views
    ├── blank.jade
    ├── cart.jade
    ├── docs.jade
    ├── _example-growl.jade
    ├── _header.jade
    ├── index.jade
    ├── layout.jade
    ├── messages.jade
    ├── newpage.jade
    ├── _pagination.jade
    ├── partials
    │   ├── acknowledgments.jade
    │   ├── api.jade
    │   ├── apps.jade
    │   ├── coffeescript.jade
    │   ├── first-steps.jade
    │   ├── growls.jade
    │   ├── jade.jade
    │   ├── optimizations.jade
    │   ├── pages.jade
    │   ├── partials.jade
    │   ├── roots.jade
    │   ├── social-login.jade
    │   ├── stylus.jade
    │   └── templates.jade
    └── products.jade

41 directories, 246 files

```
This looks like a great project. Help me use it!
