### ISSUE TITLE
Cannot find module '../../../docs/icons.js'

### ISSUE THREAD

**Issue by jerome724** [adamjgrant/kickstart#194]
Steps i did:

```
npm install
gulp build
```

Full error:

```
  at Object.Module._extensions..js (module.js:582:10)
  at Module.load (module.js:490:32)
  at tryModuleLoad (module.js:449:12)
  at Function.Module._load (module.js:441:3)
  at Module.require (module.js:500:17)
  at require (internal/module.js:20:19)
  at Liftoff.handleArguments (C:\Users\jerom\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:116:3)
  at Liftoff.<anonymous> (C:\Users\jerom\AppData\Roaming\npm\node_modules\gulp\node_modules\liftoff\index.js:198:16)
  at module.exports (C:\Users\jerom\AppData\Roaming\npm\node_modules\gulp\node_modules\flagged-respawn\index.js:17:3)
  at Liftoff.<anonymous> (C:\Users\jerom\AppData\Roaming\npm\node_modules\gulp\node_modules\liftoff\index.js:190:9)
  at C:\Users\jerom\AppData\Roaming\npm\node_modules\gulp\node_modules\liftoff\index.js:164:9
  at C:\Users\jerom\AppData\Roaming\npm\node_modules\gulp\node_modules\v8flags\index.js:108:14
  at C:\Users\jerom\AppData\Roaming\npm\node_modules\gulp\node_modules\v8flags\index.js:36:12
  at C:\Users\jerom\AppData\Roaming\npm\node_modules\gulp\node_modules\v8flags\index.js:47:7
  at _combinedTickCallback (internal/process/next_tick.js:67:7)
  at process._tickCallback (internal/process/next_tick.js:98:9)
  at Module.runMain (module.js:609:11)
  at run (bootstrap_node.js:382:7)
  at startup (bootstrap_node.js:137:9)
  at bootstrap_node.js:497:3
```

**Comment by adamjgrant** [comment]
Could you try running `make` and let me know if that changes anything? I should probably bundle that up better.

**Comment by jerome724** [comment]
i'm on windows, so i can't use 'make', or do i need to install 'make'?

**Comment by adamjgrant** [comment]
No worries. Make basically just fires off commands in the terminal for you.

So looking at build-icons (I think this is what we need to run), I believe the missing file is automatically generated.

https://github.com/adamjgrant/kickstart/blob/master/makefile

Please hold while I double check this...

**Comment by adamjgrant** [comment]
Here's essentially what needs to be run

`➜  kickstart git:(master) mkdir -p docs`
`➜  kickstart git:(master) mkdir -p docs/svgs`
`➜  kickstart git:(master) ./build.rb`

So on windows, you'd need to just create `/docs/svgs` at the root and then run build.rb

You'll only need to do this once, to create the files. After that, you can just keep running `gulp build` or just `gulp`
